<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Product\Adapters\FoosVision.Adapters.Viewer\FoosVision.Adapters.Viewer.csproj" />
    <ProjectReference Include="..\..\..\Product\Adapters\FoosVision.Protocol\FoosVision.Protocol.csproj" />
    <ProjectReference Include="..\..\..\Product\Infrastructure\FoosVision.NetDiscovery\FoosVision.NetDiscovery.csproj" />
    <ProjectReference Include="..\..\..\Product\Infrastructure\FoosVision.NetMq\FoosVision.NetMq.csproj" />
  </ItemGroup>

</Project>
