<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Formatting.Compact" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Sinks.Seq" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\FoosVision.Common\FoosVision.Common.csproj" />
    <ProjectReference Include="..\FoosVision.Settings\FoosVision.Settings.csproj" />
  </ItemGroup>
</Project>
