<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\FoosVision.UseCases\FoosVision.UseCases.csproj" />
    <ProjectReference Include="..\FoosVision.Adapters.Common\FoosVision.Adapters.Common.csproj" />
    <ProjectReference Include="..\FoosVision.Ports.Vision\FoosVision.Ports.Vision.csproj" />
    <ProjectReference Include="..\FoosVision.Protocol\FoosVision.Protocol.csproj" />
  </ItemGroup>

</Project>
